[package]
name = "sprint-kit"
version = "0.1.2"
description = "Sprint Kit for Trello"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
keyring = { version = "3", features = ["windows-native"] }
